apply from: 'gradle/scripts/helpers.gradle'

repositories {
    // Other repositories described by default:
    // CleanroomMC: https://maven.cleanroommc.com
    exclusiveContent {
		forRepository {
			maven {
				name 'CurseMaven'
				url 'https://curse.cleanroommc.com'
			}
		}
		filter {
			includeGroup 'curse.maven'
		}
	}
	exclusiveContent {
		forRepository {
			maven {
				name 'Modrinth'
				url 'https://api.modrinth.com/maven'
			}
		}
		filter {
			includeGroup 'maven.modrinth'
		}
	}
	maven {
		url = 'https://maven.blamejared.com/'
	}
	mavenLocal() // Must be last for caching to work
}

dependencies {
    // Include StripLatestForgeRequirements by default for the dev env, saves everyone a hassle
    runtimeOnly 'com.cleanroommc:strip-latest-forge-requirements:1.0'
    // Include OSXNarratorBlocker by default for the dev env, for M1+ Macs
    runtimeOnly 'com.cleanroommc:osxnarratorblocker:1.0'

    // Example - Dependency descriptor:
    // 'com.google.code.gson:gson:2.8.6' << group: com.google.code.gson, name:gson, version:2.8.6
    // 'group:name:version:classifier' where classifier is optional

    // Example - Deobfuscating dependencies:
    // rfg.deobf('curse.maven:had-enough-items-557549:4543375')
    // By wrapping a dependency descriptor in rfg.deobf() method call, the dependency is queued for deobfuscation
    // When deobfuscating, RFG respects the mapping_channel + mapping_version stated in gradle.properties

    // Example - CurseMaven dependencies:
    // 'curse.maven:had-enough-items-557549:4543375' << had-enough-items = project slug, 557549 = project id, 4543375 = file id
    // Full documentation: https://cursemaven.com/

    // Example - Modrinth dependencies:
    // 'maven.modrinth:jei:4.16.1.1000' << jei = project name, 4.16.1.1000 = file version
    // Full documentation: https://docs.modrinth.com/docs/tutorials/maven/

    // Common dependency types (configuration):
    // implementation = dependency available at both compile time and runtime
    // runtimeOnly = runtime dependency
    // compileOnly = compile time dependency
    // annotationProcessor = annotation processing dependencies
    // embed = bundle dependencies into final output artifact (no relocation)

    // Transitive dependencies:
    // (Dependencies that your dependency depends on)
    // If you wish to exclude transitive dependencies in the described dependencies
    // Use a closure as such:
    // implementation ('com.google.code.gson:gson:2.8.6') {
    //     transitive = false
    // }
    compileOnlyApi 'org.jetbrains:annotations:24.1.0'
    annotationProcessor 'org.jetbrains:annotations:24.1.0'

    implementation "CraftTweaker2:CraftTweaker2-API:" + project.version_crafttweaker
    implementation "CraftTweaker2:ZenScript:" + project.version_crafttweaker
    implementation "CraftTweaker2:CraftTweaker2-MC1120-Main:1.12-" + project.version_crafttweaker

    implementation "mezz:jei:4.27.3"
    implementation("com.cleanroommc:groovyscript:" + project.groovyscript_version) { transitive = false } // so it doesn't installs JEI

    // Debug dependencies
    compileOnly rfg.deobf("curse.maven:mantle-74924:2713386")
    if (project.debug_inspirations.toBoolean()
            || project.debug_tconstruct.toBoolean()
            || project.debug_embersconstruct.toBoolean()
            || project.debug_tinkeringwithembers.toBoolean()) {
        runtimeOnly "curse.maven:mantle-74924:2713386"
    }

    if (project.debug_tconstruct.toBoolean()
            || project.debug_embersconstruct.toBoolean()
            || project.debug_tinkeringwithembers.toBoolean()) {
        runtimeOnly "curse.maven:tinkers-antique-1242239:6752868"
        runtimeOnly "curse.maven:constructs-armory-287683:3174535"
    }

    if (project.debug_inspirations.toBoolean()) {
        runtimeOnly "curse.maven:inspirations-284007:2843007"
    }

    if (project.debug_immersiveengineering.toBoolean()) {
        runtimeOnly "curse.maven:immersive-engineering-231951:2974106"
    }

    compileOnly rfg.deobf("curse.maven:bubbles-a-baubles-fork-995393:6539774")
    if (project.debug_baubles.toBoolean()
            || project.debug_thaumcraft.toBoolean()
            || project.debug_thaumicperiphery.toBoolean()
            || project.debug_aetherworks.toBoolean()
            || project.debug_polymancy.toBoolean()
            || project.debug_planarartifice.toBoolean()) {
        runtimeOnly "curse.maven:bubbles-a-baubles-fork-995393:6539774"
    }

    compileOnly rfg.deobf("curse.maven:mysticalmechanics-300742:3006392")
    if (project.debug_mysticalmechanics.toBoolean()
            || project.debug_mysticalgears.toBoolean()
            || project.debug_mechanicalcrafting.toBoolean()) {
        runtimeOnly "curse.maven:mysticalmechanics-300742:3006392"
    }

    compileOnly rfg.deobf("curse.maven:mechanical-crafting-359671:3273914")
    if (project.debug_mechanicalcrafting.toBoolean()) {
        runtimeOnly "curse.maven:mechanical-crafting-359671:3273914"
    }

    compileOnly rfg.deobf("curse.maven:endercore-231868:4671384")
    compileOnly rfg.deobf("curse.maven:ender-io-64578:4674244")
    if (project.debug_enderio.toBoolean()) {
        runtimeOnly "curse.maven:endercore-231868:4671384"
        runtimeOnly "curse.maven:ender-io-64578:4674244"
    }

    if (project.debug_unidict.toBoolean()) {
        runtimeOnly "curse.maven:wanionlib-253043:4623135"
        runtimeOnly "curse.maven:unidict-244258:3553627"
    }

    compileOnly rfg.deobf("curse.maven:mystical-gears-317915:3206298")
    if (project.debug_mysticalgears.toBoolean()) {
        runtimeOnly "curse.maven:mystical-gears-317915:3206298"
    }

    compileOnly rfg.deobf("curse.maven:jaopca-266936:3487112") // v2.2.x
    compileOnly rfg.deobf("curse.maven:jaopca-266936:5560140") // v2.3.x
    if (project.debug_jaopca.toBoolean()) {
        runtimeOnly "curse.maven:wrapup-275153:2486198"
        runtimeOnly "curse.maven:jaopca-266936:" + project.version_jaopca
    }

    compileOnly rfg.deobf("curse.maven:aetherworks-extended-life-1003576:6210095")
    if (project.debug_aetherworks.toBoolean()) {
        runtimeOnly "curse.maven:aetherworks-extended-life-1003576:6210095"
    }

    compileOnly rfg.deobf("curse.maven:ore-stone-variants-287538:3320887")
    if (project.debug_orestonevariants.toBoolean()) {
        runtimeOnly "curse.maven:ore-stone-variants-287538:3320887"
    }

    compileOnly rfg.deobf("curse.maven:thaumcraft-223628:2629023")
    if (project.debug_thaumcraft.toBoolean()
            || project.debug_thaumicperiphery.toBoolean()
            || project.debug_polymancy.toBoolean()
            || project.debug_planarartifice.toBoolean()) {
        runtimeOnly "curse.maven:thaumcraft-223628:2629023"
        runtimeOnly "curse.maven:thaumic-jei-285492:2705304"
    }

    compileOnly rfg.deobf("curse.maven:thaumic-periphery-293505:2766866")
    compileOnly rfg.deobf("curse.maven:thaumic-augmentation-319441:6047659")
    if (project.debug_thaumicperiphery.toBoolean()) {
        runtimeOnly "curse.maven:thaumic-periphery-293505:2766866"
        runtimeOnly "curse.maven:thaumic-augmentation-319441:6047659"
    }

    compileOnly rfg.deobf("curse.maven:polymancy-394626:3065950")
    if (project.debug_polymancy.toBoolean()) {
        runtimeOnly "curse.maven:thaumic-wands-393922:5053794"
        runtimeOnly "curse.maven:polymancy-394626:3065950"
    }

    compileOnly rfg.deobf("curse.maven:embersified-303584:2621911")
    if (project.debug_embersified.toBoolean()) {
        runtimeOnly "curse.maven:embersified-303584:2621911"
    }

    compileOnly rfg.deobf("curse.maven:soot-extended-life-982730:5156451")
    if (project.debug_soot.toBoolean()) {
        runtimeOnly "curse.maven:soot-extended-life-982730:5156451"
    }

    compileOnly rfg.deobf("curse.maven:embersconstruct-359414:" + project.version_embersconstruct)
    if (project.debug_embersconstruct.toBoolean()) {
        runtimeOnly "curse.maven:embersconstruct-359414:" + project.version_embersconstruct
    }

    compileOnly rfg.deobf("curse.maven:tinkering-with-embers-306685:2636808")
    if (project.debug_tinkeringwithembers.toBoolean()) {
        runtimeOnly "curse.maven:tinkering-with-embers-306685:2636808"
    }

    compileOnly rfg.deobf("curse.maven:planar-artifice-409849:3668551")
    if (project.debug_planarartifice.toBoolean()) {
        runtimeOnly rfg.deobf("curse.maven:planar-artifice-409849:3668551")
    }

    compileOnly rfg.deobf("curse.maven:embersified-extended-984998:5184690")
    if (project.debug_embersifiedextended.toBoolean()) {
        runtimeOnly "curse.maven:embersified-extended-984998:5184690"
    }

    compileOnly rfg.deobf("curse.maven:more-climate-551276:4293417")
    if (project.debug_moreclimate.toBoolean()) {
        runtimeOnly "curse.maven:more-climate-551276:4293417"
    }

    compileOnly rfg.deobf("curse.maven:gedgetry-core-282775:2633658")
    compileOnly rfg.deobf("curse.maven:gedgetry-machines-282776:2634495")
    compileOnly rfg.deobf("curse.maven:gedgetry-transmission-282777:2633660")
    if (project.debug_gadgetry.toBoolean()) {
        runtimeOnly "curse.maven:gedgetry-core-282775:2633658"
        runtimeOnly "curse.maven:gedgetry-machines-282776:2634495"
        runtimeOnly "curse.maven:gedgetry-transmission-282777:2633660"
    }

    compileOnly rfg.deobf("curse.maven:spartan-weaponry-278141:4467344")
    compileOnly rfg.deobf("curse.maven:spartan-weaponry-arcana-unofficial-620760:3836926")
    if (project.debug_spartanweaponry.toBoolean()) {
        runtimeOnly "curse.maven:spartan-weaponry-278141:4467344"
        runtimeOnly "curse.maven:spartan-weaponry-arcana-unofficial-620760:3836926"
    }

    compileOnly rfg.deobf("curse.maven:emberforged-887375:5582901")
    compileOnly rfg.deobf("curse.maven:minefantasy-reforged-431996:4666619")
    compileOnly rfg.deobf("curse.maven:codechicken-lib-1-8-242818:2779848")
    if (project.debug_emberforged.toBoolean()) {
        runtimeOnly "curse.maven:codechicken-lib-1-8-242818:2779848"
        runtimeOnly "curse.maven:emberforged-887375:5582901"
        runtimeOnly "curse.maven:minefantasy-reforged-431996:4666619"
    }

    compileOnly rfg.deobf("curse.maven:ae2-extended-life-570458:5411078")
    if (project.debug_ae2.toBoolean() || project.debug_appliedintegrations.toBoolean()) {
        runtimeOnly "curse.maven:ae2-extended-life-570458:5411078"
    }

    compileOnly rfg.deobf("curse.maven:applied-integrations-301924:2866504")
    if (project.debug_appliedintegrations.toBoolean()) {
        runtimeOnly "curse.maven:applied-integrations-301924:2866504"
    }

    compileOnly rfg.deobf("curse.maven:dynaores-1056043:5541366")
    if (project.debug_rawores.toBoolean()) {
        runtimeOnly "curse.maven:dynaores-1056043:5541366"
    }

    compileOnly rfg.deobf("curse.maven:ic2-classic-242942:5800761")
    if (project.debug_ic2classic.toBoolean()) {
        runtimeOnly "curse.maven:ic2-classic-242942:5800761"
    }

    compileOnly rfg.deobf("curse.maven:simpledifficulty-360779:3613814")
    compileOnly rfg.deobf("curse.maven:survival-tools-1120531:5807832")
    if (project.debug_survivaltools.toBoolean()) {
        runtimeOnly "curse.maven:simpledifficulty-360779:3613814"
        runtimeOnly "curse.maven:survival-tools-1120531:5807832"
    }

    compileOnly rfg.deobf("curse.maven:valkyrielib-245480:2691542")
    compileOnly rfg.deobf("curse.maven:valkyriecompat-289532:2691540")
    compileOnly rfg.deobf("curse.maven:environmental-tech-245453:2691536")
    if (project.debug_environmentaltech.toBoolean()) {
        runtimeOnly "curse.maven:valkyrielib-245480:2691542"
        runtimeOnly "curse.maven:environmental-tech-245453:2691536"
        if (project.debug_ic2classic.toBoolean()) {
             runtimeOnly "curse.maven:valkyriecompat-289532:2691540"
        }
    }

    compileOnly rfg.deobf("curse.maven:railcraft-51195:3853491")
    compileOnly rfg.deobf("curse.maven:railway-depot-worker-1031521:6812208")
    if (project.debug_railcraft.toBoolean()) {
        runtimeOnly "curse.maven:railcraft-51195:3853491"
        runtimeOnly "curse.maven:railway-depot-worker-1031521:6812208"
    }

    // Runtime dependencies
    runtimeOnly rfg.deobf("curse.maven:the-one-probe-community-edition-885670:5824252")
    runtimeOnly rfg.deobf("curse.maven:topalldependents-1120632:5808089") // updated version of the one probe addons
}