VERSION = ${mod_version}
MOD_ID = ${mod_id}
MOD_NAME = ${mod_name}
DEPENDENCIES = after:mysticalmechanics;required-after:mixinbooter@[${mixin_booter_version},);after:environmentaltech;after:thaumicperiphery;after:thaumicaugmentation;